
```{r}
#This is a example of Survival Analysis from the datacamp tutorial: https://www.datacamp.com/community/tutorials/survival-analysis-R
# It pretends to study the probability of death comparing patients who has ovarian cancer
```

```{r}
library(survival)
library(survminer)
library(tidyverse)
```


```{r}
#Loading the dataset ovarian
# "This dataset comprises a cohort of ovarian cancer patients and respective clinical information, including the time patients were tracked until they either died or were lost to follow-up (futime), whether patients were censored or not (fustat), patient age, treatment group assignment, presence of residual disease and performance status."

data(ovarian)
glimpse(ovarian)

```


```{r}
# Dichotomize age and change data labels
ovarian$rx <- factor(ovarian$rx, 
                     levels = c("1", "2"), 
                     labels = c("A", "B"))
ovarian$resid.ds <- factor(ovarian$resid.ds, 
                           levels = c("1", "2"), 
                           labels = c("no", "yes"))
ovarian$ecog.ps <- factor(ovarian$ecog.ps, 
                          levels = c("1", "2"), 
                          labels = c("good", "bad"))

# Data seems to be bimodal
hist(ovarian$age) 

```

```{r}
#Cutting of the age to transform it to binary

ovarian <- ovarian %>% mutate(age_group = ifelse(age >=50, "old", "young"))
ovarian$age_group <- factor(ovarian$age_group)

```

```{r}

# Fit survival data using the Kaplan-Meier method
surv_object <- Surv(time = ovarian$futime, event = ovarian$fustat)
surv_object


```

```{r}
#Lets take a look at comparision of treatment A and treatment B

fit1 <- survfit(surv_object ~ rx, data = ovarian)
summary(fit1)
```


```{r}
#Ploting it
ggsurvplot(fit1, data = ovarian, pval = TRUE)

```

```{r}
# By the chart, the treatment B performs better than treatment A over the time, p-value is not significant, 
# considering 0.05
# Examine prdictive value of residual disease status
fit2 <- survfit(surv_object ~ resid.ds, data = ovarian)
ggsurvplot(fit2, data = ovarian, pval = TRUE)

```


```{r}
#In this case, we can observ that patients with residual disease have a worse prognosis compared to patients without residual disease

#Lets perfom the Cox model, in this, we can observe the covariates at the context

# Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ rx + resid.ds + age_group + ecog.ps, 
                   data = ovarian)
ggforest(fit.coxph, data = ovarian)


```


```{r}
#By this chart, we can analyse better, compared to his respective classes, the probabiliry of hazard is greater in # bad treatment and in patients who have residual disease, and patients who are younger the probability of hazard
# is smaller, and the test is significand by the p-value.
# The two test answer diferent questions

```